name: Deploy to VPS

on:
  push:
    branches:
      - main  # Ou qualquer branch que você queira usar para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          rsync -avz --delete --exclude='.git*' ./ danieloliveiradev@146.59.154.239:/var/www/html/html-css-js -e "ssh -p 2222 -o StrictHostKeyChecking=no"